const Movie = require("../models/Movie");

const movies = [
  {
    title: "The Batman",
    synopsis: "Batman investigates a series of crimes in Gotham City.",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIMCpS3OjmxGAhuR99vetHATrUSMK2Cih6TB10Dnk9op5yB-y4DEVQsw9h3814Z8MirrCe&s=10",
    duration: 175,
    rating: 4.2,
  },
  {
    title: "Inception",
    synopsis: "A thief enters dreams to steal and plant ideas.",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRyuWmayVBvqjd1MxTKpRgauq2cCtUzb7Q9QvaFTkAuxAU_EYMoCE3wBuJeftxIzf0grreIw&s=10",
    duration: 148,
    rating: 4.6,
  },
  {
    title: "Interstellar",
    synopsis: "Astronauts travel through space to save humanity.",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9oW0XQlu1lo1G_49M-YwGzKR6rUg-CtflZj07HfbT8d2GwKWg",
    duration: 169,
    rating: 4.5,
  },
  {
    title: "The Dark Knight",
    synopsis: "Batman faces the Joker in Gotham City.",
    posterUrl: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQkUywIUXDjHSQJIaNHYVs08osgBpF5Ot-xmB_omyEZeeRP9Xug",
    duration: 152,
    rating: 4.9,
  },
  {
    title: "Avengers: Endgame",
    synopsis: "Heroes unite to undo a devastating loss.",
    posterUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRXef9DJnZiq5az0UnjkmvkQufOQ5MFnF7HATYRUXN913swRuH1",
    duration: 181,
    rating: 4.3,
  },
  {
    title: "Spider-Man: No Way Home",
    synopsis: "Spider-Man faces threats from multiple universes.",
    posterUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQSdnOkKE9dBN68bYDK4FNPszoUkeG4X7XCJCTsgpfCP-EY9GIx",
    duration: 148,
    rating: 4.7,
  },
  {
    title: "Iron Man",
    synopsis: "A genius builds a powerful armored suit.",
    posterUrl: "https://upload.wikimedia.org/wikipedia/en/0/02/Iron_Man_%282008_film%29_poster.jpg",
    duration: 126,
    rating: 4.2,
  },
  {
    title: "Captain America: The First Avenger",
    synopsis: "A soldier becomes a super-powered hero.",
    posterUrl: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR9zwYQE_lvp7VS4cQbGM85Ry-9LTlhYoKwAVf__ROHz374Nhm6",
    duration: 124,
    rating: 3.8,
  },
  {
    title: "Thor",
    synopsis: "A god learns humility on Earth.",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBcJJt7e5d0I3t6G4_I2GfWYG2bg5LjHPEP0-0Vg_S6tfpLRHd1AokgqzxLMfigK6XhD4DtJRyrHFjT5w-6bAme-DXxiA0Wnm86jofWvY&s",
    duration: 115,
    rating: 3.6,
  },
  {
    title: "Black Panther",
    synopsis: "A king defends his advanced nation.",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1MSjVz4AlBMvl3RD0eXqenCdZbowXC-2uGUcgYGSrtuOdsVAGWVYmJ24_wB54zLkMxaVU&s=10",
    duration: 134,
    rating: 4.1,
  },
  {
    title: "Doctor Strange",
    synopsis: "A surgeon becomes a master of mystic arts.",
    posterUrl: "https://lumiere-a.akamaihd.net/v1/images/p_doctorstrange_19918_516f94d3.jpeg",
    duration: 115,
    rating: 3.9,
  },
  {
    title: "Guardians of the Galaxy",
    synopsis: "A group of misfits save the galaxy.",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSipIjfcRc0CpCf5YnLK12ubygGW0efN4p9SvwaNx9Li2ppZRsqh3nji1cel-r3qPrsGtrcPI_f54baOolJE-IBbsO0WyAP8rQE33Edvg&s",
    duration: 121,
    rating: 4.3,
  },
  {
    title: "The Matrix",
    synopsis: "A hacker discovers reality is a simulation.",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnBeu1JQWwPEDWp2IkSRCEuyStU0rGLgMCzIpGG_km2q62MNOKv6Ve-bvX16mQEYTea7fL472bDf_jcIuGOkPQGCrBhYOscCdT5rsdew&s=10",
    duration: 136,
    rating: 4.8,
  },
  {
    title: "John Wick",
    synopsis: "A retired assassin seeks revenge.",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMGkVjiOwsLdMUXdfFsqzk6IB3dQk14egq5uwAhEppeRmJZ1wPENnO6tMmSs4l3kcYFP4bJKcDqnXPBpYVK4lCIh3S3nTESsQBnpzXaKYV&s=10",
    duration: 101,
    rating: 4.1,
  },
  {
    title: "Gladiator",
    synopsis: "A general seeks justice in ancient Rome.",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3W-oZZ7a0QKn_KYR0bAgDm9Y7aKvosndgf9TX_wCNGTyNtVtl8hHAs8wyAstEGQUVe29Q71P6xnd6m5qd_tJBrrQVUDVNKOhAXxJ-gA&s=10",
    duration: 155,
    rating: 4.2,
  },
  {
    title: "Titanic",
    synopsis: "A love story aboard a doomed ship.",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlcQXin_CNozAFkv_SSihe5eZ_lvDD5nBqCmQT3xPf6KLlqHloIo5cBRGqwuy8pjuIiZrqoA&s=10",
    duration: 195,
    rating: 4.5,
  },
  {
    title: "Jurassic Park",
    synopsis: "Dinosaurs run loose in a theme park.",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR3mjAx8C6gUIbB2bRwF18EZ1O__iF92Xu7-QkdC8aRI-vDD2b6v0j_0_uClVbjOI_voH-SJ4AdpLRfM3mAWjG91_uJn8lXw9cvh2GUw&s=10",
    duration: 127,
    rating: 4.7,
  },
  {
    title: "Avatar",
    synopsis: "Humans clash with an alien world.",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHuY484VNuH6DQea0DwgHsAYgZCbR0a-jxmLbciys8zoHjd1JJZut8oRSdcQE0lQnAyckwew&s=10",
    duration: 162,
    rating: 4.0,
  },
  {
    title: "The Lion King",
    synopsis: "A young lion learns to be king.",
    posterUrl: "https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg",
    duration: 88,
    rating: 4.8,
  },
  {
    title: "Toy Story",
    synopsis: "Toys come to life when humans leave.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZTA3OWVjOWItNjE1NS00NzZiLWE1MjgtZDZhMWI1ZTlkNzYwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    duration: 81,
    rating: 4.7,
  },
  {
    title: "Finding Nemo",
    synopsis: "A father searches the ocean for his son.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMTc5NjExNTA5OV5BMl5BanBnXkFtZTYwMTQ0ODY2._V1_.jpg",
    duration: 100,
    rating: 4.5,
  },
  {
    title: "WALL-E",
    synopsis: "A robot cleans Earth in the future.",
    posterUrl: "https://upload.wikimedia.org/wikipedia/en/4/4c/WALL-E_poster.jpg",
    duration: 98,
    rating: 4.8,
  },
  {
    title: "The Incredibles",
    synopsis: "A family of superheroes reunites.",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQBpXOzrtmLdQv97a3pG77I7VQn-63xlaYAO8IQhkYN9m2NY66yHbBm_8o2sp0wuuiTW8laK6ovZv31EFflRWZAJoocdBLITUgyFMSJaAFSw&s=10",
    duration: 115,
    rating: 4.6,
  },
  {
    title: "Shrek",
    synopsis: "An ogre rescues a princess.",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQg_Lj-AwA3TKS-FSwZ8c8V0zDIA4cnGrMGz0tGfAzakmcYhWr6ndm6EXpSrYYXCprXW9d6&s=10",
    duration: 90,
    rating: 4.3,
  },

];

module.exports = async () => {
  await Movie.bulkCreate(movies);
  console.log("🎬 Movies seeded");
};
